name: Daily Fact Generator

on:
  schedule:
    - cron: '0 6 * * *'  # Exécution tous les jours à Paris : 8h00 en été et 7h00 en hiver
  workflow_dispatch:  # Permet de lancer manuellement l'action via l'interface GitHub

jobs:
  generate-fact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # à updater le cas échéant

      - name: Install dependencies
        run: |
          npm install

      - name: Debug secrets
        run: |
          echo "UTS_MISTRAL_API_KEY is set: ${{ secrets.UTS_MISTRAL_API_KEY != '' }}"
          echo "FACT_GENERATION_PROMPT is set: ${{ secrets.FACT_GENERATION_PROMPT != '' }}"
          echo "MISTRAL_AGENT_FACTGENERATOR_ID is set: ${{ secrets.MISTRAL_AGENT_FACTGENERATOR_ID != '' }}"


      - name: Run the daily fact generator
        env:
          UTS_MISTRAL_API_KEY: ${{ secrets.UTS_MISTRAL_API_KEY }}  # Utilise les secrets pour tes clés API
          FACT_GENERATION_PROMPT: ${{ secrets.FACT_GENERATION_PROMPT }}
          MISTRAL_AGENT_FACTGENERATOR_ID: ${{ secrets.MISTRAL_AGENT_FACTGENERATOR_ID }}
        run: |
          node -e "require('./controllers/facts.js').dailyFactGenerator();"
